Fix build with -DBUILD_TEST=TRUE
Otherwise it fails with "test/test.cpp:49:14: error: 'qVariantValue'
was not declared in this scope". qVariantValue is a obsolete
workaround for MSVC 6, which was released 1998 and thus seems ancient
enough to change this.

REVIEW: 127334